mystore/comment/urls.py
from django.urls import path
from . import views

app_name='comment'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('list_comment/', views.list_comment, name='list_comment'),
    path('', views.index, name='index'),  
    path('update_comment/<int:pk>', views.update_comment, name='update_comment'),
    path('delete_comment/<int:pk>', views.delete_comment, name='delete_comment'),   
]

mystore/element/urls.py
from django.urls import path
from . import views

app_name='element'

urlpatterns = [
    path('add/', views.add, name='add'),
    # path('add2/', views.add2, name='add2'),
    path('', views.index, name='index'),
     
]

mystore/mystore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("comment.urls")),
    path('elements/', include("element.urls")),
]

mystore/comment/models.py
from django.db import models
from element.models import Element
# Create your models here.


class Comment(models. Model):
    text = models.TextField()
    date_posted = models.DateTimeField(auto_now=True)
    element = models.ForeignKey(Element, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return 'Comment #{}'.format(self.id)

mystore/element/models.py
from django.db import models
from django.core.exceptions import ValidationError
# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.title
    
class Type(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)

    def __str__(self):
        return self.title

class Element(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, default=6.10)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    def clean(self):
        if self.price < 0:
            raise ValidationError('Price cannot be 0')

mystore/comment/forms.py
from django.forms import ModelForm
from django import forms
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
    

# widget en forma de clase

class OtherWidget(forms.TextInput):
    class Media:
        css = {
            'all': ["pretty.css"],
            
        }
        js = ["animations.js", "actions.js"]

mystore/element/forms.py
from django import forms

from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError
from .models import Type, Category, Element
from django.utils.text import slugify



class ElementForm(forms.Form):
    title = forms.CharField(label='Title', max_length=255,  validators=[MinLengthValidator(3, message='Very short! (min %(limit_value)d) (current %(show_value)d)')])
    slug = forms.SlugField(label='Slug', max_length=255, min_length=3)
    description = forms.CharField(label='Description', initial='Content initial', widget=forms.Textarea)
    price = forms.DecimalField(label='Price', decimal_places=2, max_digits=5, required=True)
    type = forms.ModelChoiceField(label='Type', queryset=Type.objects.all(), initial=1)
    category = forms.ModelChoiceField(label='Category', queryset=Category.objects.all(), initial=2)
 

 #validacion para que el titulo sea unico
    def clean_title(self):
        title = self.cleaned_data['title']
        if Element.objects.filter(title=title).exists():
            raise ValidationError('Title already exists')
        return title


#Validacion global 
    def clean(self):
        form_data = self.cleaned_data
        if form_data['slug'] != slugify(form_data['title']):
            self._errors['slug'] = ["slug do not match with title"]
            del form_data['slug']
        return

# class ElementModelForm(forms.ModelForm):
#     class Meta:
#         model = Element
#         fields = ('title', 'slug', 'description', 'price', 'type', 'category')

mystore/comment/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Comment
from .forms import CommentForm
from django.core.paginator import Paginator
from django.http import Http404

# Create your views here.


def list_comment(request):
    comment = Comment.objects.all()

    return render(request, 'list_comment.html', {'comment': comment})


#CRUD COMMENTS
def index(request):
    comments = Comment.objects.all()
    #comments = get_list_or_404(Comment, pk__gt=14)
    paginator = Paginator(comments, 5)
    page_number = request.GET.get('page')
    comments_page = paginator.get_page(page_number)

    return render(request, 'index.html',{'comments': comments_page})



def update_comment(request, pk):

    comment = get_object_or_404(Comment, pk=pk)
    # try:
    #     comment = Comment.objects.get(pk=pk)

    # except Comment.DoesNotExist:
    #     raise Http404
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = CommentForm(instance=comment)
    return render(request, 'add.html', {'form': form})



def delete_comment(request, pk):
    comment = Comment.objects.get(pk=pk)

    if request.method == 'POST':
        comment.delete()
        return redirect('/')
   
    
# def add(request):
#      if (request.method == 'GET'):
#          pass
#      if (request.method == 'POST'):
#          if request.POST.get('text') != '':
#              comment = Comment()
#              comment.text = request.POST.get('text')
#              comment.save()
#          else:
#              print('Campo vacio')
#      return render(request, 'add.html')


def add(request):
    if (request.method == 'POST'):
        form = CommentForm(request.POST)
        form.save()
        return redirect('/')
    else:
        form = CommentForm()
    return render(request, 'add.html', {'form': form})

mystore/element/views.py
from django.shortcuts import redirect, render
from django.http import request
from .forms import ElementForm #, ElementModelForm
from .models import Element
from django.core.paginator import Paginator

# Create your views here.
def add(request):
    if request.method == 'POST':
        form = ElementForm(request.POST)
        if form.is_valid():
            element = Element()
            element.title = form.cleaned_data['title']
            element.slug = form.cleaned_data['slug']
            element.description = form.cleaned_data['description']
           #element.price = form.cleaned_data['price']
            element.category = form.cleaned_data['category']
            element.type = form.cleaned_data['type']
            element.save()
        return redirect('element:index')
    else:
        form = ElementForm()
    
    return render(request, 'element/add.html', {'form': form})



# def add2(request):
#     if request.method == 'POST':
#         form = ElementModelForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('/')
#     else:
#         form = ElementModelForm()
    
#     return render(request, 'element/add.html', {'form': form})



def index(request):
    elements = Element.objects.all()
    paginator = Paginator(elements, 10)

    page_number = request.GET.get('page')
    return render(request, 'element/index.html', {'elements': paginator.get_page(page_number)})

mystore/comment/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>pagina para agregar</h1>
    <P>Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis aspernatur, enim perferendis, magnam voluptatem in libero sapiente alias ipsam porro repellat hic consequatur commodi sint eum reiciendis earum ad? Non.</P>
        
    <!-- <form action="{% url 'list_comment' % }" method="POST">
       
        <label for="" >Text</label>
        <textarea required  name="text"></textarea>
        {% csrf_token %}
        <button type="submit">Send</button>
    </form> -->

    <form action="" method="POST">
        {{form}}
        {% csrf_token %}
        <button type="submit">Send</button>
    </form>    
</body>
</html>

mystore/comment/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Lista de comentarios</h2>
    <a href="{% url 'comment:add' %}" target="_blank" >Add</a>

    {% for comment in comments %}
        <p>{{ comment.text }}</p>
        <br>
        <p>{{ comment.date_posted }}</p>

        <a href="{% url 'comment:update_comment' comment.id %}">Editar</a>
        
        <form action="{% url 'comment:delete_comment' comment.id %}" method="POST">
            {% csrf_token %}
        <input type="submit" value="Delete">

        </form>
    {% endfor %}

    <nav>
        <ul class="paginator justify-content-center">
            {% if comments.has_previous %}

                <li class="page-item">
                    <a class="page-link" href="?page={{ comments.previous_page_number }}">Prev</a>
                </li>
            
            {% endif %}

            <li class="page-item">
                {% for i in comments.paginator.page_range %}
                    <a class="page-link" href="?page={{ i }}"></a>
                    {{i}}
                {% endfor %}
            </li>
            
            {% if comments.has_next %}

                <li class="page-item">
                    <a class="page-link" href="?page={{ comments.next_page_number }}">Next</a>
                </li>
            
            {% endif %}
            
        </ul>
    </nav>

    
</body>
</html>

mystore/comment/templates/list_comment.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
    <title>Comentarios</title>

</hea>

<body>
    
    <h1>Lista de Comentarios</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Comments</th>
                <th scope="col">Date Posted</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

            </tr> {% for comment in comment %} <tr>

                <td>{{ comment.id }}</td>
                <td>{{ comment.text }}</td>
                <td>{{ comment.date_posted }}</td>
                <td> 
                <button class="btn btn-warning">Editar</button> 
                <button class="btn btn-danger">Eliminar</button> 
                </td>
            </tr> {% endfor %}
        </tbody>
    </table>
</body>

</html>

mystore/element/templates/element/add.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
        aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add elements</h1>
                    <button type="button" class="btn-close" onclick="history.back();" data-bs-dismiss="modal" aria-label="Close"></button>


                </div>
                <div class="modal-body">
                    {% if form.errors %}
                    <div class="alert alert-danger">
                        {% for field in form %}
                        {% for error in field.errors %}
                        <div>
                            <strong>{{ field.label }}:</strong> {{ error }}
                        </div>
                        {% endfor %}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <form class="row g-3" method="post">
                        {% csrf_token %}
                        <div class="col-12">
                            <table class="table table-bordered table-hover table-sm">
                                <tbody>
                                    <!-- Campo: Title -->
                                    <tr>
                                        <th scope="row">{{ form.title.label }}</th>
                                        <td>{{ form.title }}</td>
                                    </tr>
                                    <!-- Campo: Slug -->
                                    <tr>
                                        <th scope="row">{{ form.slug.label }}</th>
                                        <td>{{ form.slug }}</td>
                                    </tr>
                                    <!-- Campo: Description -->
                                    <tr>
                                        <th scope="row">{{ form.description.label }}</th>
                                        <td>{{ form.description }}</td>
                                    </tr>
                                    <!-- Campo: Price -->
                                    <tr>
                                        <th scope="row">{{ form.price.label }}</th>
                                        <td>{{ form.price }}</td>
                                    </tr>
                                    <!-- Campo: Type -->
                                    <tr>
                                        <th scope="row">{{ form.type.label }}</th>
                                        <td>{{ form.type }}</td>
                                    </tr>
                                    <!-- Campo: Category -->
                                    <tr>
                                        <th scope="row">{{ form.category.label }}</th>
                                        <td>{{ form.category }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-12">
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Send</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Incluye el JavaScript de Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

    <!-- Script para abrir el modal automáticamente -->
    <script>
        // Verifica si el parámetro "openModal" está en la URL
        const urlParams = new URLSearchParams(window.location.search);
        const openModal = urlParams.get('openModal');

        // Si el parámetro está presente, abre el modal
        if (openModal === 'true') {
            const myModal = new bootstrap.Modal(document.getElementById('exampleModal'));
            myModal.show();
        }
    </script>
</body>

</html>

mystore/element/templates/element/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-5">

        <a href="add?openModal=true" class="btn btn-success">Create +</a>
        <!-- Button trigger modal -->
        <!--<button type="button" class="btn btn-primary"  href="/elements/add" data-bs-toggle="modal" data-bs-target="#staticBackdrop">-->

        </button>
    </div>
    <div class="container mt-5">
        <table class="table table-hover">
            <tr>
                <th>#</th>
                <th>Title</th>
                <th>Category</th>
                <th>Type</th>
                <th>Price</th>
                <th>Date</th>
                <th>Actions</th>

            </tr>
            {% for e in elements %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{e.title}}</td>
                <td>{{e.category.title}}</td>
                <td>{{e.type}}</td>
                <td>{{e.price}}</td>
                <td>{{e.created}}</td>
                <td>
                    <a href="" class="btn btn-warning">Ver</a>
                    <a href="" class="btn btn-success">Editar</a>
                    <a href="" class="btn btn-danger">Eliminar</a>
                </td>
            </tr>
            {% endfor %}

        </table>
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                {% if elements.has_previous %}

                <a class="page-link" href="?page={{ elements.previous_page_number }}">Previous</a>

                {% endif %}
            </li>

            
                {% for i in elements.paginator.page_range %}
                <li class="page-item"></li><a class="page-link" href="?page={{ i }}">{{i}}</a></li>

                {% endfor %}
            
            <li class="page-item">
                {% if elements.has_next %}
                <a class="page-link" href="?page={{ elements.next_page_number }}">Next</a>
                {% endif %}
            </li>
        </ul>
    </nav>

    <!-- Incluye el JavaScript de Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous">

        </script>

</body>

</html>